# hash-identificacao: c1b444ca998748a9ea402722c0bbb8b8039fd818f462591a31651fd968c93ad1

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=dados-pessoais

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

#Formata o JSON das respostas com indentação
spring.jackson.serialization.INDENT_OUTPUT=true

# --- Banco de Dados H2 (em mem�ria) ---
spring.datasource.url=jdbc:h2:mem:dadospessoais;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Console Web do H2 (dispon�vel em http://localhost:8080/h2-console) ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
