# hash-identificacao: c1b444ca998748a9ea402722c0bbb8b8039fd818f462591a31651fd968c93ad1

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=dados-pessoais

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

#Formata o JSON das respostas com indentação
spring.jackson.serialization.INDENT_OUTPUT=true
